### ISSUE TITLE
Hot spring disable in config?

### ISSUE THREAD

**Issue by AquaticLava** [SoraZodia/hotwater#2]
I would like it if you could have hot springs be disabled in the config file because when i run into a hot spring biome i crash due to water hitting the hot spring water. Thanks!

**Comment by SoraZodia** [comment]
Looks like a bug, I'll see if I can get it fix. Providing a crash report would also help me track down what might be causing the problem.

**Comment by AquaticLava** [comment]
Crash: http://pastebin.com/7u7F4NB0

**Comment by SoraZodia** [comment]
This should be fixed in v1.0.5.
