### ISSUE TITLE
You shouldn't be using our BucketHandler.

### ISSUE THREAD

**Issue by asiekierka** [SoraZodia/hotwater#3]
Please get your own BucketHandler, as BC's is internal (and it doesn't work with BC 7.1+, making your mod crash).

(Renaming will work fine.)

**Comment by parcel31u** [comment]
For realz, I want to use both buildcraft and hot water at the same time because I enjoy hot water so much!

**Comment by SoraZodia** [comment]
Should be fixed now, decided to make my own handler.
