### ISSUE TITLE
Spring Water & Hot Water Buckets Can't Place their Liquids

### ISSUE THREAD

**Issue by WenXin20** [SoraZodia/hotwater#4]

**Comment by SoraZodia** [comment]
What version are you using? That should had been fixed in v3.0.1.

**Comment by WenXin20** [comment]
Ok thanks, I didn't realize I wasn't using the most recent version, I was using 3.0 instead of 3.0.1

**Comment by WenXin20** [comment]
Ok thanks, I didn't realize I wasn't using the most recent version, I was using 3.0 instead of 3.0.1, though for some reason it won't store in the chisels and bits mod tanks.

**Comment by SoraZodia** [comment]
I would have to check that out. This issue will be closed though.
